name: Generate Fixed SBOM
on:
  push:
    branches: [ master ] # master(またはmain)ブランチに更新があったら実行
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          output-file: ./juice-shop-fixed-sbom.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: fixed-sbom
          path: ./juice-shop-fixed-sbom.json
